image_speed = 1;
death_sound = calculator;
sound_timer = 0;
next_sound_time = 0;
shoot_cooldown = 0;
shoot_rate = 2;
player = obj_player_winter;
hp = 1000;
sound_timer = 0;
next_sound_time = random_range(5, 15);
player_detected = false;
burst_shots = 0; // Количество выстрелов в очереди
max_burst_shots = 10; // Максимальное количество выстрелов в очереди
burst_cooldown = 0;
burst_rate = 0.2; // Интервал между выстрелами в очереди
burst_delay = 0; // Задержка между очередями
min_burst_delay = 1; // Минимальная задержка между очередями
max_burst_delay = 3; // Максимальная задержка между очередями
